### ISSUE TITLE
SSH port 22 Permission denied

### ISSUE THREAD

**Issue by dirtdiver512** [desaster/kippo#180]
All,
I have a few issues.

One after an install the start up script is looking for a pid file in the /var/run/kippo/kipo.pid, but that doesnt exist after reboot.

Also if is try and start the service after changing it from port 2222, the default setting,  to 22 i get a permission denied.

any thoughts?

**Comment by Waseem-farooqui** [comment]
You have changed it to port `22` from `2222`??
have you restart the `ssh service` ?

**Comment by akaasjager** [comment]
Because port 22 can only be opened by root, you cannot use it. You should not run Kippo with root privileges!

The solution is to 
- run real sshd on (for example) 2222
- run kippo on (again, example) 3333
- configure IPTables to forward requests from internet for port 22 to 3333 on the host:

   [internet] -> [port 22] -> [iptables] -> [port 3333] -> [kippo]

You can find examples for IPTables on *NixCraft:
http://www.cyberciti.biz/faq/linux-port-redirection-with-iptables/

**Comment by dirtdiver512** [comment]
thanks I ended up needing to use iptables, any other solution was not reliable
