### ISSUE TITLE
Error on starting kippo

### ISSUE THREAD

**Issue by lambis7** [desaster/kippo#213]
Hi when I try to start kippo with the following command 'sudo ./start.sh' I get the following output:
"twistd (the Twisted daemon) 14.0.2
Copyright (c) 2001-2014 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
ERROR: You must not run kippo as root!"

Then when I try to start it as simple user with just ./start.sh I get the following error:
'twistd (the Twisted daemon) 14.0.2
Copyright (c) 2001-2014 Twisted Matrix Laboratories.
See LICENSE for details.
Starting kippo in the background...
Loading dblog engine: mysql
Generating new RSA keypair...

Failed to load application: [Errno 13] Permission denied: 'data/ssh_host_rsa_key.pub'

How can I fix that?

**Comment by desaster** [comment]
check your file and directory permissions

**Comment by lambis7** [comment]
@desaster file permisions are rw-r--r-- change them to what?

**Comment by desaster** [comment]
sorry, to be more precise, check the ownership of the files and directories.

**Comment by lambis7** [comment]
I changed the permission of folder /etc/ssh which contains the file ssh_host_rsa_key.pub from root to my user. Now file permissions are owner: myuser group: root but I still get the same error

**Comment by desaster** [comment]
That seems like a wrong thing to do; the /etc/ssh directory has nothing to do with kippo, as the keys for kippo are generated in kippo's data directory by default.

Right now you're messing with the keys of your openssh daemon, which may have bad effects on your system.

Sorry, but I recommend you do not proceed further with kippo, since it's a security related application that requires good knowledge of the underlying operating system to use safely.

**Comment by lambis7** [comment]
I fixed it. Thanks
