### ISSUE TITLE
License

### ISSUE THREAD

**Issue by robputt796** [desaster/kippo#229]
Hi Upi,

I had a quick query about the license for Kippo, although the COPYRIGHT notice allows modification, redistribution and so on... is this actually based on any commonly used open source license? It looks similar to Apache 2.0 to me, however I might be wrong. If possible could we officially license Kippo under one of the existing open source licenses? I am sure updating the license could open more possibilities for contribution.

Best Regards,

Rob

**Comment by desaster** [comment]
The license is the 3-cause BSD license. I tend to use it because it's very non-restrictive.

I haven't spent much time researching licenses though, maybe some other license might have been better.

As for contributions, I don't the license has caused any issues. Only major issue was that I haven't been an active maintainer of the project. Cowrie has done a better job in that regard, I suggest you check it out:

https://github.com/micheloosterhof/cowrie

**Comment by robputt796** [comment]
Hey,

Thanks for the info, my query was really mainly in relation to advising people about our interactive honey pot port HonSSH as we had some contributors asking for clarification on the license and we essentially inherited the Kippo license.  You can checkout the project here... https://github.com/tnich/honssh

Best Regards,

Rob
